FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

WORKDIR /workspace

# 安裝系統依賴（如果有需要可加）
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    fontconfig \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# copy requirements
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt